# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 528)
        Dialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        Dialog.setSizeGripEnabled(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.wordToNum = QtWidgets.QCheckBox(Dialog)
        self.wordToNum.setObjectName("wordToNum")
        self.verticalLayout.addWidget(self.wordToNum)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.searchButton = QtWidgets.QPushButton(Dialog)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.copySelectedButton = QtWidgets.QPushButton(Dialog)
        self.copySelectedButton.setObjectName("copySelectedButton")
        self.verticalLayout_2.addWidget(self.copySelectedButton)
        self.showMappingsButton = QtWidgets.QPushButton(Dialog)
        self.showMappingsButton.setObjectName("showMappingsButton")
        self.verticalLayout_2.addWidget(self.showMappingsButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "مولد نظام المذكرات الصوتي للعربية"))
        self.listWidget.setSortingEnabled(True)
        self.wordToNum.setText(_translate("Dialog", "من كلمة إلى رقم"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "أدخل رقمًا"))
        self.searchButton.setText(_translate("Dialog", "بحث"))
        self.searchButton.setShortcut(_translate("Dialog", "Ctrl+Return"))
        self.copySelectedButton.setText(_translate("Dialog", "نسخ الكلمات المحددة"))
        self.copySelectedButton.setShortcut(_translate("Dialog", "Ctrl+C"))
        self.showMappingsButton.setText(_translate("Dialog", "جدول التحويل"))
